# Generated by Django 3.2.16 on 2023-12-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название меню')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слаг меню')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название предмета')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слаг предмета')),
                ('menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='menu.item')),
            ],
            options={
                'verbose_name': 'предмет меню',
                'verbose_name_plural': 'Предметы меню',
            },
        ),
    ]
