# Generated by Django 3.2.16 on 2023-12-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_item_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг предмета'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг меню'),
        ),
    ]
